### ISSUE TITLE
Proposal: Store Templates in $HOME

### ISSUE THREAD

**Issue by rawkode** [openfaas/faas-cli#154] opened 2017-10-09 18:21 UTC
## Expected Behaviour
When I run a `faas-cli` command, it should store all templates within `$HOME/.openfaas/templates`

## Current Behaviour
When I run `faas-cli`, if the templates don't exist in the current directory, it will download and extract them to the current directory

**Comment by alexellis** [comment] 2017-10-09 19:53
Interesting idea. The reason it stores in the current directory is to allow multiple sets of templates to be maintained and downloaded fresh for each stack.

**Comment by Lewiscowles1986** [comment] 2017-10-27 19:09
I'm against `$HOME` because it silo's to a single user. I worry would be a hot-mess like nvm. What about `/opt/faas/templates` ?

**Comment by alexellis** [comment] 2017-11-29 23:37
Templates go in the current directory at the moment. This is by design and allows them to be customized. With `template pull` we have the possibility to have templates with the same name in different folders. I'm going to close the issue, we may revisit.

**Closed by alexellis** 2017-11-29 23:37 UTC
Labels: proposal
