### ISSUE TITLE
lang: Dockerfile can not success build on latest 0.6.4

### ISSUE THREAD

**Issue by rayhero** [openfaas/faas-cli#358] opened 2018-03-29 04:03 UTC
In previous version 0.5.2, I can set my yml like below:
  auto-hotspot-openmvg-test:
    lang: Dockerfile
    handler: ./sample/auto-hotspot
    image: gcr.io/auto-hotspot-test
    fprocess: "node handler.js"

and use faas-cli build --filter=auto-hotspot-test -f ./auto-hotspot.yml to build the faas image

after I upgrade to latest 0.6.4, I get the error message below:

[0] > Building auto-hotspot-openmvg-test.
2018/03/29 11:55:06 Language template: Dockerfile not supported. Build a custom Dockerfile instead.

## Expected Behaviour
It should work like old version to build the docker image

## Current Behaviour
use lang: Dockerfile will not trigger docker build command

## Possible Solution
Currently I manually to use docker build to build the image

## Steps to Reproduce (for bugs)
1. create a yml using lang: Dockerfile
2. trigger faas-cli build -f file.yml

## Context
Currently I manually to user docker command to build my image
## Your Environment
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes (FaaS-netes)
* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment] 2018-03-29 07:05
Use a lowercase dockerfile please

**Comment by iyovcheva** [comment] 2018-03-29 08:58
Derek add label: support

**Comment by alexellis** [comment] 2018-03-29 09:29
@iyovcheva there is a work-around for this as I gave above. Please can you put this on your list to check over? The code in the CLI used to allow Dockerfile and dockerfile for deployments.

**Comment by iyovcheva** [comment] 2018-03-29 14:42
@rayhero I cannot reproduce.
Tested this with 0.6.4 on Kubernetes with [helloc](https://github.com/openfaas/faas/tree/master/sample-functions/CHelloWorld) function from the samples, which uses `Dockerfile` language and it builds successfully.

Can you share more details about your function? (may be there is some typo/extra space/etc in your yaml)

**Comment by alexellis** [comment] 2018-03-29 15:35
I can confirm the same - I was unable to reproduce the error. The only time you may see this error is if you don't have any templates in the folder when deploying or building.

Try to run `faas template pull` first and make sure your templates are the latest version.

I'm going to close the issue but let us know if you still have difficulties after trying the above steps.

**Closed by alexellis** 2018-03-29 15:35 UTC
Labels: support
