### ISSUE TITLE
Question: Node.js template code sharing between functions

### ISSUE THREAD

**Issue by kobynet** [openfaas/faas-cli#464] opened 2018-07-23 11:12 UTC
Assume we want to create CRUD rest service using node.js template. Functions share some code (for example bootstrap of the environment. since faas-cli forces me to have single handler.js file, what is the best way to do this without code redundancy ? 

## Expected Behaviour
yml file allows to pick my own handler file

## Current Behaviour
handler.js is picked without any other option

## Possible Solution
Not sure if it kind of overrides the single function single responsibility concept, but being able to pick my own handler file (maybe copying the custom handler (for example create.js/delete.js) file as handler.js in build directory)

**Comment by rgee0** [comment] 2018-07-23 18:46
Possible duplicate. Ref: #322

**Comment by kobynet** [comment] 2018-07-24 06:29
Thanks @rgee0 , missed that one.

**Comment by alexellis** [comment] 2018-07-24 22:46
Interesting, so you'd want the exact same code, just somehow with different names and handlers?

I'd suggest you use a single function and switch on a query string parameter.

**Comment by kobynet** [comment] 2018-07-25 07:11
@alexellis with having switch i might end up writing the whole controller in single handler file.

There is an example of restful service using openfaas [here](https://github.com/testdrivenio/openfass-node-restful-api) but it actually has very small bootstrapping code and it is copied from function to function which is what i am trying to avoid.

In addition, when team needs to manage rest service project where most code is used by the rest functions (under faas concept), i think it make sense to have all functions in single root folder and have different yaml file for deployment. 

Any thoughts?

**Comment by viveksyngh** [comment] 2018-07-29 16:04
Derek add label: question

**Comment by viveksyngh** [comment] 2018-07-29 16:04
Dereke add label: support

**Comment by ivanayov** [comment] 2018-08-21 11:41
@kobynet Does this proposal work for you - [#322#issuecomment-410613647](https://github.com/openfaas/faas-cli/issues/322#issuecomment-410613647) ?

I'm going to close this issue, as it's a duplicate of #322, but feel free to comment on the other issue.

Ivana

**Comment by ivanayov** [comment] 2018-08-21 11:41
Derek close

**Closed by ivanayov** 2018-08-21 11:41 UTC
Labels: question, support
