### ISSUE TITLE
Adding Support for Build ARG from FASS-CLI

### ISSUE THREAD

**Issue by s8sg** [openfaas/faas-cli#355] opened 2018-03-23 03:49 UTC
Adding support for having build time argument with FAAS Cli would help to provide argument in the build process 

## Expected Behaviour
The flag `--arg` can be used to specify the argument   
```bash
--arg <key>=<value>
```  
A command might look like:   

```bash
faas-cli build -f https://domain/path/myfunctions.yml --arg apikey=$VALUE
```

Which would eventually be passed as build argument in the docker build process for the function image
```bash
docker build --build-argument apikey=key ...
```

## Current Behaviour
Currently `environment` can be specified in `stack.yml`. Although for variable that is needed at build time can only be configured at Dockerfile. It is possible to have a KEY that would change for every build. Currently the `--build-arg` that is being passed are
```bash
http_proxy=<>
https_proxy=<>
```

## Possible Solution
```bash
faas-cli build -f https://domain/path/myfunctions.yml --arg apikey=$VALUE
```
which would eventually pass the argument as a `--build-arg` while building the docker image 

and/or 

that can be used to set an Env variable in `Dockerfile`:
```Dockerfile
ARG apikey

ENV APIKEY=$apikey
```

## Context
In a automated CI steps, I need to pass secret key argument to the functions, which is not fixed and change for different builds. Its easier to pass them via `faas-cli` rather than changing the `Dockerfile` file every time

**Comment by iyovcheva** [comment] 2018-03-23 08:43
Derek add label: proposal

**Comment by iyovcheva** [comment] 2018-03-23 09:40
@s8sg Thanks for proposal.
Actually this is a duplicate of [#262](https://github.com/openfaas/faas-cli/issues), so will close the issue, but feel free to comment/share ideas/contribute to the other open issue.

**Comment by iyovcheva** [comment] 2018-03-23 09:41
Derek close

**Closed by iyovcheva** 2018-03-23 09:41 UTC
Labels: proposal
