### ISSUE TITLE
[Blocking] Testing needed for 0.6.9 release

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#410] opened 2018-05-14 14:39 UTC
The CLI has not been released since 0.6.5. Some PRs which were merged from the community broke any deployments from YAML files / manual definitions and the store. 

Before cutting the next release I'd like some help testing the following:

* Deploying via YAML files

This should also exercise the new flag for Swarm: `--send-registry-auth`

* Deploying manually via CLI arguments

This should also exercise the new flag for Swarm: `--send-registry-auth`

* Deploying via store

For each test case please exercise edge-cases and not just the happy path - that is how we got into the state of having to pull 3 minor release of the CLI. Coding is only one part of the PR process - the other is being able to stand by work produced through testing - both automated and manual.

This has caused confusion upstream with the `homebrew` package: #406 

## Testing

```
git clone https://github.com/openfaas/faas-cli
cd faas-cli
./build_redist.sh
```

This produces faas-cli / faas-cli-darwin which you can then use from this directory or install to /usr/local/bin.

**Comment by iyovcheva** [comment] 2018-05-14 20:59
Did some basic testing. Looks ok.

```
$ ../faas-cli-darwin store deploy SentimentAnalysis -a
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Function sentimentanalysis already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://127.0.0.1:8080/function/sentimentanalysis
```

```
$ ../faas-cli-darwin deploy -f test.yml --gateway http://165.227.52.52:8080 -a
Deploying: test.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Function test already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://165.227.52.52:8080/function/test

```

```
$ ../faas-cli-darwin deploy --image=alexellis2/node_info -name=node_info --gateway http://165.227.52.52:8080 -a
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 200 OK.
URL: http://165.227.52.52:8080/function/node_info
```

Will proceed tomorrow with some different use-cases to check for regression.

**Comment by ericstoekl** [comment] 2018-05-15 05:45
One thing I have noticed is that when attempting to deploy a function with `faas-cli deploy -a` and the `stack.yml` functions section looks like this:

```
functions:
  myFunc:
    lang: go
    handler: ./myFunc
    image: myfunc
```

It will fail to deploy and throw an error:

```
Unexpected status: 400, message: Invalid registry auth
```

Is this expected? Shouldn't it be okay with not authenticating because it's implied that the image is from the local registry?

**Comment by alexellis** [comment] 2018-05-15 06:35
So you're saying it should ignore the author string is the image points at the local library. Sounds fair - this was a miss from the original PR.

Who is going to volunteer to pick up the change?

**Comment by iyovcheva** [comment] 2018-05-15 10:32
I can work on this

**Comment by alexellis** [comment] 2018-05-15 12:19
Strangely I cannot reproduce that error @ericstoekl - I'm on Docker for Mac. @iyovcheva can you reproduce the error from Eric?

**Comment by alexellis** [comment] 2018-05-15 12:32
I have pushed https://github.com/openfaas/faas-cli/commit/b7c6f0bf79e871e8e74661c56520d5010df5ac5b to fix the behavior highlighted by Eric.

**Comment by alexellis** [comment] 2018-05-15 12:49
I've cut a pre-release build of 0.6.9 - please can you switch over to this binary for testing?

https://github.com/openfaas/faas-cli/releases/tag/0.6.9

Alex

**Comment by iyovcheva** [comment] 2018-05-15 12:50
I reproduced on Mac OS. [b7c6f0b](https://github.com/openfaas/faas-cli/commit/b7c6f0bf79e871e8e74661c56520d5010df5ac5b) fixes the issue.

Are we good to promote 0.6.9 with this fix?

**Comment by iyovcheva** [comment] 2018-05-15 13:53
It failed deploying via CLI 

```
$ ./faas-cli-darwin deploy --image=alexellis2/node_info -name=node_info --gateway http://<ip>:8080 -a

Deploying: shrink-image.

Debug info: ===========
warnInsecureGateway = true
gateway = http://<ip>:8080
registryAuth = <non-empty>
=====================

WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Debug info: ===========
update  = true
statusCode  = 404
=====================

Unexpected status: 400, message: Invalid registry auth

Deploying: ruby-echo.

WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Unexpected status: 400, message: Invalid registry auth

Deploying: url-ping.

WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

^C

```

The same issue was reproduced with some other images:
`--image=hello-python -name=tmp`
` --image=docwareiy/sorter -name=sorter`

Also tries to deploy images different than the image argument, as visible in the output above.
E.g.
`Deploying: nodejs-echo.`
`Deploying: shrink-image.`

Deploying with YAML worked with the same `registryAuth`:

```
$ ./faas-cli-darwin deploy -f test.yml --gateway http://<ip>:8080 -a
Deploying: test.

Debug info: ===========
warnInsecureGateway = true
gateway = http://<ip>:8080
registryAuth = <non-empty>
=====================

WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Function test already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://<ip>:8080/function/test
```

**Comment by alexellis** [comment] 2018-05-15 13:56
You can't deploy manually when you have a stack file in the directory. You need to change out first or delete it.

**Comment by iyovcheva** [comment] 2018-05-15 14:03
I ran it from /faas-cli and forgot about the `stack.yml` there. So it tried to deploy the functions listed in it.

**Comment by iyovcheva** [comment] 2018-05-15 14:36
There are no more issues from my side. Retested all the examples above and the deployment works well.

**Comment by iyovcheva** [comment] 2018-05-17 08:04
Closing as 0.6.9 is released

**Comment by iyovcheva** [comment] 2018-05-17 08:05
Derek close

**Closed by iyovcheva** 2018-05-17 08:05 UTC

**Comment by alexellis** [comment] 2018-06-16 23:47
Thank you @iyovcheva

**Comment by alexellis** [comment] 2018-06-16 23:47
Derek lock
