### ISSUE TITLE
faas-cli new with lang 'Dockerfile' results in empty function

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#317] opened 2018-02-06 04:38 UTC
## Expected Behaviour

When running `faas-cli new <func_name> --lang Dockerfile` on Linux (tested on Ubuntu 16.04) you get an empty function folder.

## Current Behaviour

```
~/github/functions/cli2func $ faas new nmap --lang Dockerfile
2018/02/05 20:34:41 No templates found in current directory.
2018/02/05 20:34:41 Attempting to expand templates from https://github.com/openfaas/templates.git
2018/02/05 20:34:41 Fetched 11 template(s) : [csharp dockerfile go go-armhf node node-arm64 node-armhf python python-armhf python3 ruby] from https://github.com/openfaas/templates.git
Folder: nmap created.
...

Function created in folder: nmap
Stack file written: nmap.yml
~/github/functions/cli2func $ ls
nmap  nmap.yml  template
~/github/functions/cli2func $ ls nmap/
~/github/functions/cli2func $ 
```

## Possible Solution

Either add `Dockerfile/` folder to the `openfaas/templates` repository (the `Dockerfile/` folder would be identical to the `dockerfile/` folder), or apply my patch:
https://github.com/ericstoekl/faas-cli/commit/54a293da30221f8fd0351381e355f0d1b865c17e

## Steps to Reproduce (for bugs)

1. Get on ubuntu linux
2. `faas new func --lang Dockerfile`
3. Check for existence of `func/Dockerfile`
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
17.12.0
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 16.04
* Link to your project or a code example to reproduce issue:

**Comment by kenfdev** [comment] 2018-02-06 04:53
Confirmed this bug occurs. But only on Ubuntu (not Mac)

Below is Mac version (Dockerfile exists)
```
[➜  ~ ] faas new nmap --lang Dockerfile
2018/02/06 13:20:09 No templates found in current directory.
2018/02/06 13:20:09 Attempting to expand templates from https://github.com/openfaas/templates.git
2018/02/06 13:20:11 Fetched 11 template(s) : [csharp dockerfile go go-armhf node node-arm64 node-armhf python python-armhf python3 ruby] from https://github.com/openfaas/templates.git
Folder: nmap created.
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|


Function created in folder: nmap
Stack file written: nmap.yml
[➜  ~ ] ll nmap
total 8
-rw-r--r--  1 kenfukuyama  staff   512B  2  6 13:20 Dockerfile
```

Below is Ubuntu version (Dockerfile not existing)

```
root@ubuntu1:~# faas new nmap --lang Dockerfile
2018/02/06 13:26:27 No templates found in current directory.
2018/02/06 13:26:27 Attempting to expand templates from https://github.com/openfaas/templates.git
2018/02/06 13:26:28 Fetched 11 template(s) : [csharp dockerfile go go-armhf node node-arm64 node-armhf python python-armhf python3 ruby] from https://github.com/openfaas/templates.git
Folder: nmap created.
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|


Function created in folder: nmap
Stack file written: nmap.yml
root@ubuntu1:~# ls
nmap  nmap.yml  template
root@ubuntu1:~# ls nmap
root@ubuntu1:~#
# ^empty!!
```

**Comment by ericstoekl** [comment] 2018-02-06 05:04
It's very strange that it doesn't occur on Mac. Thanks so much for testing @kenfdev !!

**Comment by kenfdev** [comment] 2018-02-06 05:22
Haven't looked at the code but this probably occurs due to Mac and Windows file system not being case sensitive while Ubuntu(and most linux distros) _**is case sensitive**_.

Ubuntu is probably failing to copy because the directory `template/Dockerfile` doesn't exist. (only `template/dockerfile` )

**Comment by alexellis** [comment] 2018-02-06 09:18
@itscaro helped with this change.. perhaps he can also test on Windows and then we can work out whether there is an easy fix for this?

**Comment by itscaro** [comment] 2018-02-06 09:36
I will investigate

**Comment by itscaro** [comment] 2018-02-06 12:35
Should we use `dockerfile` as only choice instead of `dockerfile` and `Dockerfile`?

Dockerfile is the only exception that the language name is not in the same case as listed:

`2018/02/06 13:30:35 Fetched 11 template(s) : [csharp dockerfile go go-armhf node node-arm64 node-armhf python python-armhf python3 ruby]`

It might cause confusion, we can add a message to tell users when they do not respect the case.

Example: Python3 is refused since it's not a known language template

```
faas new --lang Python3 test
Python3 is unavailable or not supported
```

**Comment by alexellis** [comment] 2018-02-06 12:41
If we change dockerfile then we break compatibility. It's a special-case, so maybe we can add an extra rule?

**Comment by itscaro** [comment] 2018-02-06 15:13
OK for deprecation notice & special case for now :)

**Comment by rgee0** [comment] 2018-02-06 16:08
The issue is in `copy.go`, or the hand-off into `copy.go`.  Everywhere prior to that we handle the case thing.  Being consistently case-insensitive tends to make for happier users.

**Comment by itscaro** [comment] 2018-02-13 09:27
Finally I went for converting all Dockerfile to dockerfile internally and showing nothing to users.

**Comment by alexellis** [comment] 2018-02-13 16:22
Sounds good to me @itscaro thank you for your help with this.

**Comment by itscaro** [comment] 2018-02-17 17:29
@ericstoekl there is still another PR for build process

**Comment by alexellis** [comment] 2018-02-17 19:00
OK @itscaro

**Comment by alexellis** [comment] 2018-03-01 12:09
Derek close: all PRs merged.

**Closed by alexellis** 2018-03-01 12:09 UTC
Labels: bug
