### ISSUE TITLE
Add `--all` option to `faas-cli rm` to quickly remove all functions

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#203] opened 2017-11-04 06:28 UTC
## Expected Behaviour

When you issue the `--all` flag to `faas-cli`, you will remove all the deployed functions.

## Current Behaviour

It's more difficult to quickly remove all functions deployed.

## Possible Solution

Get list of functions by calling `proxy.ListFunctions()`, call `proxy.DeleteFunction()` on each returned function.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Any
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Both
* Operating System and version (e.g. Linux, Windows, MacOS):
All
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment] 2017-11-04 08:22
This needs a design review around the UX/DX. We are really coupled to the yaml files, so we'd have to validate there was no -f parameter passed in or a command line name either.

**Comment by rgee0** [comment] 2017-11-04 10:22
Feels like something that should be dependent on multitenancy. Perhaps something to revisit?

**Comment by ericstoekl** [comment] 2017-11-04 19:11
Derek add label revisit

**Comment by ericstoekl** [comment] 2017-11-04 19:11
Derek add label: revisit

**Comment by ericstoekl** [comment] 2017-11-04 19:12
Derek add label: proposal

**Comment by alexellis** [comment] 2017-11-06 16:32
Closing to focus work.. please feel free to keep commenting.

**Closed** 2017-11-06 16:32 UTC
Labels: proposal, revisit

**Comment by yogeek** [comment] 2018-03-12 10:52
I have the same need : in order to quickly deploy openfaas with custom functions, I clone the faas repo, use the "deploy-stack.sh" from the faas repo and then I have all the samples functions by default. 
If I want to have only my custom functions, I currently have 2 solutions :

- duplicate the docker-compose.yml of openfaas, remove all samples functions and deploy from it
(but this implies keeping my version of docker-compose.yml up to date with the latest evolutions...)
- deploy from the original docker-compose.yml, remove all sample functions and deploy my own 

I prefer the second option but currently, to do this, I must remove sample function one by one.
So in this case, a "-all" option for the remove command of faas-cli makes sense to me.

Obviously, another option would be to add in openfaas repo a version of docker-compose.yml without the samples. In my cas, it would be the quickest and easiest solution to begin with. 
What do you think ?

**Comment by alexellis** [comment] 2018-03-12 10:55
Let's look at remove all sample functions from the initial stack. I'd like help with this, but we will need to update all blogs and documentation also.

**Comment by yogeek** [comment] 2018-03-12 11:05
@alexellis maybe you do not need to replace the initial stack but just to add another stack file without the sample functions (e.g. docker-compose.without-samples.yml) to leave the choice to the user to deploy one or the other. It would have less implications on the blogs and docs, wouldn't it ?

**Comment by iyovcheva** [comment] 2018-03-12 15:44
@yogeek, the error is because a provider is not referenced in the `docker-compose.yml`.

`faas-cli remove -f ./docker-compose.yml` will not work for removing the functions, as it's not in a format that will be successfully parsed from the `remove` command.

**Comment by alexellis** [comment] 2018-03-12 16:40
`faas remove --all` is dangerous because as of #351 we will have four overrides

* ARG --gateway
* YAML -f / --yaml (or if default file is in directory stack.yml) (I count this as two)
* ENV-VAR OPENFAAS_FN
* Finally the default

So `faas remove --all` could have unexpected behaviour. The experience might need refining, it'd be better to move this to a new issue i.e. https://github.com/openfaas/faas/issues/478

**Comment by alexellis** [comment] 2018-03-12 16:41
Derek lock: please move conversation to new issue or linked issue.
